export const tokens = {
  colors: {
    light: {
      surface: '#fbfbf8',
      paper: '#ffffff',
      ink: '#111111',
      muted: '#6b6b6b',
      subtle: '#9d9797',
      divider: '#d4d4d4',
      accent: '#000000',
      focus: '#000000',
    },
    dark: {
      surface: '#111111',
      paper: '#000000',
      ink: '#eeeeee',
      muted: '#9d9d9d',
      subtle: '#808080',
      divider: '#333333',
      accent: '#ffffff',
      focus: '#ffffff',
    },
  },
  typography: {
    sans: [
      'ui-sans-serif',
      'system-ui',
      '-apple-system',
      'BlinkMacSystemFont',
      '"Segoe UI"',
      'Roboto',
      'sans-serif',
    ].join(', '),
    serif: [
      'ui-serif',
      'Georgia',
      'Cambria',
      '"Times New Roman"',
      'Times',
      'serif',
    ].join(', '),
    sizes: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '2rem',
    },
  },
  spacing: {
    0: '0',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    6: '1.5rem',
    8: '2rem',
    12: '3rem',
    16: '4rem',
  },
  radii: {
    none: '0',
    sm: '2px',
    md: '4px',
    lg: '8px',
    kindle: '24px',
  },
  motion: {
    flash: '150ms',
    fast: '100ms',
    base: '200ms',
  },
} as const
